#! /bin/bash

cont_count=$1
echo "creating container"

for i in 'seq $cont_count'

do sleep 2;
 echo "====================================="
 echo "creating conatiners www.gamutgart"
sleep 2;
 docker run --name www.gamtkart$i -d -it --rm nageshvkn/gamutkart-img /bin/bash

echo "gamutkart conatiner is created"
echo "##############################################"
done

docker inspect --format {{.Networksettins.Networks.bridge.IpAddress}} 'docker ps -a -q'>IPS.txt
